# Generated by Django 4.2.5 on 2023-09-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_articles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
