# Generated by Django 4.2.5 on 2023-09-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_m_articles_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('ref', models.CharField(max_length=128)),
                ('desgn', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('qty', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='m_articles',
        ),
    ]
