# Generated by Django 4.2.5 on 2023-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_articles_delete_m_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='articles',
        ),
    ]
