# Generated by Django 4.2.5 on 2023-09-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_articles_delete_m_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_purchase', models.FloatField(default=0.0)),
                ('p_sale', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
