# Generated by Django 4.2.4 on 2023-09-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_delivery_supplier_invoice_supplier_order_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_list_customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('qty', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='order_list_supplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('qty', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
