# Generated by Django 4.2.4 on 2023-09-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_order_list_customer_order_list_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list_customer',
            name='id_article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.article'),
        ),
    ]
