# Generated by Django 4.2.4 on 2023-09-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_order_list_customer_id_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_customer',
            name='id_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.order_customer'),
        ),
        migrations.AddField(
            model_name='invoice_customer',
            name='id_delivery_customer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='models.delivery_customer'),
        ),
        migrations.AddField(
            model_name='order_customer',
            name='id_customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.customer'),
        ),
        migrations.AddField(
            model_name='payment_customer',
            name='id_invoice_customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.invoice_customer'),
        ),
    ]
