# Generated by Django 4.2.4 on 2023-09-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_delivery_customer_id_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_supplier',
            name='id_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.order_supplier'),
        ),
        migrations.AddField(
            model_name='invoice_supplier',
            name='id_delivery_supplier',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='models.delivery_supplier'),
        ),
        migrations.AddField(
            model_name='order_list_supplier',
            name='id_article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.article'),
        ),
        migrations.AddField(
            model_name='order_list_supplier',
            name='id_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.order_supplier'),
        ),
        migrations.AddField(
            model_name='order_supplier',
            name='id_supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.supplier'),
        ),
        migrations.AddField(
            model_name='payment_supplier',
            name='id_invoice_supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.invoice_supplier'),
        ),
    ]
