# Generated by Django 4.2.5 on 2023-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_delivery_supplier_id_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery_customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice_customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_list_customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
