# Generated by Django 4.2.5 on 2023-09-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_alter_customer_id_alter_delivery_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_supplier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice_supplier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_list_supplier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_supplier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_supplier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
